services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: greenhill_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - camp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d greenhill_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  telegram_bot:
    build: .
    container_name: greenhill_bot_container
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/greenhill_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${BOT_USERNAME}
      ADMIN_TG_ID: ${ADMIN_TG_ID}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/images:/app/images:ro
    networks:
      - camp_network
    restart: always

volumes:
  postgres_data:

networks:
  camp_network:
    driver: bridge