spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/greenhill_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME:greenhill_camp_bot}

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG